Add base readme
tokoro-koshi/tokoro pull request #2
Opened 2024-11-17 08:53 UTC by shliakhetko

Getting started is commented, in order to not make guesses on env and organization namings

2024-12-04 23:30 UTC, AndrewVynnytskyi requested changes
Напиши нормальний README, а не кидай пусту файл, лентяй

2024-12-07 18:40 UTC, rojikaru requested changes

2024-12-07 18:40 UTC, rojikaru commented on README.md
> +> ## 🗂 Monorepo Structure
Project structure

2024-12-08 12:22 UTC, rojikaru approved these changes

2024-12-09 10:11 UTC, olehio-p approved these changes

2024-12-09 10:11 UTC, Ania-Savchuk approved these changes

2024-12-09 19:11 UTC, AndrewVynnytskyi approved these changes

2024-12-09 19:29 UTC, merged