Update production backend
tokoro-koshi/tokoro pull request #5
Opened 2024-12-07 18:35 UTC by AndrewVynnytskyi

2024-12-07 18:36 UTC, rojikaru approved these changes, later dismissed

2024-12-07 19:01 UTC, rojikaru approved these changes, later dismissed

2024-12-07 19:05 UTC, olehio-p requested changes
Use the “plural” name to denote the collection resource archetype.

2024-12-07 20:30 UTC, shliakhetko submitted a review, later dismissed

2024-12-09 10:01 UTC, rojikaru approved these changes

2024-12-09 10:02 UTC, olehio-p approved these changes

2024-12-09 10:10 UTC, Ania-Savchuk approved these changes

2024-12-09 10:54 UTC, shliakhetko approved these changes

2024-12-09 19:13 UTC, merged